import Sidebar from "@/Componant/ui/SideBar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};



const layout = ({children}:{children:React.ReactNode}) => {
    return (
        <div className="min-h-screen ">
            <div className="flex flex-col md:flex-row">

                <div className="w-full md:w-[18%]">
                    <Sidebar />
                </div>


                <div className="w-full md:w-[80%] mr-4 md:ml-10">
                    {children}
                </div>
            </div>
        </div>
    );
};

export default layout;